#!/usr/bin/env bash

set -u

APP_DIR="${SERVER_CONTEXT_SCANNER_HOME:-$HOME/server-context-scanner}"
REPORT_DIR="$APP_DIR/reports"
mkdir -p "$REPORT_DIR"

MODE="summary"

usage() {
  cat <<'EOF'
Usage:
  scan_server_context.sh [--full] [--help]

Modes:
  default   Generate a concise AI-friendly server context summary.
  --full    Generate a detailed diagnostic report.
  --help    Show this help message.
EOF
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --full)
      MODE="full"
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
  shift
done

TS="$(date '+%Y%m%d_%H%M%S')"
REPORT_FILE="$REPORT_DIR/server_context_$TS.md"
LATEST_FILE="$REPORT_DIR/server_context_latest.md"

write() {
  printf '%s\n' "$*" >> "$REPORT_FILE"
}

section() {
  write ""
  write "## $1"
  write ""
}

cmd() {
  local title="$1"
  local command="$2"

  write "### $title"
  write ""
  if [ "$MODE" = "full" ]; then
    write '```bash'
    write "$ $command"
    write '```'
    write ""
  fi
  write '```text'
  bash -lc "$command" >> "$REPORT_FILE" 2>&1 || true
  write '```'
  write ""
}

project_cmd() {
  local title="$1"
  local dir="$2"
  local command="$3"
  local display_dir

  display_dir="$(printf '%q' "$dir")"

  write "### $title"
  write ""
  if [ "$MODE" = "full" ]; then
    write '```bash'
    write "$ cd -- $display_dir && $command"
    write '```'
    write ""
  fi
  write '```text'
  (
    cd -- "$dir" && bash -lc "$command"
  ) >> "$REPORT_FILE" 2>&1 || true
  write '```'
  write ""
}

short_value() {
  bash -lc "$1" 2>/dev/null | head -1 || true
}

has_file() {
  local dir="$1"
  local file="$2"
  if [ -f "$dir/$file" ]; then
    printf 'yes'
  else
    printf 'no'
  fi
}

has_any_compose_file() {
  local dir="$1"
  if [ -f "$dir/docker-compose.yml" ] || [ -f "$dir/docker-compose.yaml" ] || [ -f "$dir/compose.yml" ] || [ -f "$dir/compose.yaml" ]; then
    printf 'yes'
  else
    printf 'no'
  fi
}

safe_project_dirs() {
  find /opt "$HOME" \
    -maxdepth 4 \
    -type f \( \
      -name "package.json" -o \
      -name "docker-compose.yml" -o \
      -name "docker-compose.yaml" -o \
      -name "compose.yml" -o \
      -name "compose.yaml" -o \
      -name "Dockerfile" -o \
      -name "ecosystem.config.js" \
    \) \
    -not -path "*/node_modules/*" \
    -not -path "*/.next/*" \
    -not -path "*/dist/*" \
    -not -path "*/build/*" \
    -not -path "*/out/*" \
    -not -path "*/coverage/*" \
    -not -path "*/.turbo/*" \
    -not -path "*/.output/*" \
    -not -path "*/.vercel/*" \
    -not -path "*/.cache/*" \
    -not -path "*/reports/*" \
    -not -path "*/.npm/*" \
    -not -path "*/.local/*" \
    -print0 2>/dev/null \
    | xargs -0 -r dirname -- \
    | sort -u
}

init_report() {
  local title="$1"

  {
    echo "# $title"
    echo ""
    echo "- Generated at: $(date '+%Y-%m-%d %H:%M:%S %Z')"
    echo "- Hostname: $(hostname 2>/dev/null || true)"
    echo "- User: $(whoami 2>/dev/null || true)"
    echo "- Mode: $MODE"
    echo "- Scanner directory: $APP_DIR"
    echo "- Report file: $REPORT_FILE"
    echo ""
    echo "> This report is generated by a read-only scanner. It should not include secret values."
    echo "> Permission denied output means the current user cannot inspect that resource; it does not prove the resource does not exist."
  } > "$REPORT_FILE"
}

write_summary_host() {
  section "1. Host"
  write "- OS: $(short_value "if [ -f /etc/os-release ]; then . /etc/os-release; echo \"\$PRETTY_NAME\"; else uname -a; fi")"
  write "- Kernel: $(short_value "uname -r")"
  write "- Uptime: $(short_value "uptime -p || uptime")"
  write "- CPU cores: $(short_value "nproc || true")"
  write "- Memory: $(short_value "free -h | awk '/^Mem:/ {print \"total=\" \$2 \", used=\" \$3 \", free=\" \$4 \", available=\" \$7}'")"
  write "- Swap: $(short_value "free -h | awk '/^Swap:/ {print \"total=\" \$2 \", used=\" \$3 \", free=\" \$4}'")"
  write "- Root disk: $(short_value "df -h / | awk 'NR==2 {print \"size=\" \$2 \", used=\" \$3 \", avail=\" \$4 \", use=\" \$5}'")"
}

write_summary_runtime() {
  section "2. Runtime"
  write "- Node: $(short_value "node -v || echo not-found")"
  write "- npm: $(short_value "npm -v || echo not-found")"
  write "- npx: $(short_value "npx -v || echo not-found")"
  write "- Git: $(short_value "git --version || echo not-found")"
  write "- Python: $(short_value "python3 --version || echo not-found")"
  write "- pip: $(short_value "pip3 --version | awk '{print \$1, \$2}' || echo not-found")"
  write "- PM2: $(short_value "command -v pm2 >/dev/null 2>&1 && pm2 -v || echo not-found")"
  write "- Docker: $(short_value "command -v docker >/dev/null 2>&1 && docker --version || echo not-found")"
  write "- Docker Compose: $(short_value "command -v docker >/dev/null 2>&1 && docker compose version || echo not-found")"
  write "- systemd: $(short_value "systemctl --version 2>/dev/null | head -1 || echo not-found")"
  write "- Nginx: $(short_value "command -v nginx >/dev/null 2>&1 && nginx -v 2>&1 || echo not-found")"
  write "- Nginx active: $(short_value "command -v nginx >/dev/null 2>&1 && systemctl is-active nginx 2>/dev/null || echo unknown")"
  write "- Nginx enabled: $(short_value "command -v nginx >/dev/null 2>&1 && systemctl is-enabled nginx 2>/dev/null || echo unknown")"
}

write_summary_ports() {
  section "3. Ports"
  cmd "Common ports quick check" "for p in 80 443 3000 3001 3010 3011 5000 5173 8000 8080; do if ss -lntp 2>/dev/null | grep -q \":\$p \"; then echo \"\$p: occupied\"; ss -lntp 2>/dev/null | grep \":\$p \" | head -3; else echo \"\$p: free_or_not_listening\"; fi; done"
}

write_nginx_routes_summary() {
  local routes

  write "### Nginx routes"
  write ""
  write '```text'

  if ! command -v nginx >/dev/null 2>&1; then
    routes="Nginx not found."
  else
    routes="$(
      find /etc/nginx/sites-enabled /etc/nginx/conf.d -type f -print 2>/dev/null | sort | while IFS= read -r file; do
        [ -f "$file" ] || continue
        awk -v file="$file" '
          /^[[:space:]]*#/ { next }
          {
            line=$0
            sub(/[[:space:]]+#.*/, "", line)
          }
          line ~ /^[[:space:]]*server[[:space:]]*\{/ {
            name=""
            next
          }
          line ~ /^[[:space:]]*server_name[[:space:]]+/ {
            sub(/^[[:space:]]*server_name[[:space:]]+/, "", line)
            sub(/[[:space:]]*;.*/, "", line)
            name=line
            next
          }
          line ~ /^[[:space:]]*proxy_pass[[:space:]]+/ {
            route=line
            sub(/^[[:space:]]*proxy_pass[[:space:]]+/, "", route)
            sub(/[[:space:]]*;.*/, "", route)
            if (name != "") print name " -> " route
            else print "(unknown in " file ") -> " route
          }
        ' "$file"
      done
    )"
    [ -n "$routes" ] || routes="No Nginx proxy routes found."
  fi

  printf '%s\n' "$routes" >> "$REPORT_FILE"
  write '```'
  write ""
}

write_summary_services() {
  section "4. Running Services"
  cmd "PM2 apps" "if ! command -v pm2 >/dev/null 2>&1; then echo 'PM2 not found.'; elif ! command -v python3 >/dev/null 2>&1; then echo 'Python not found; cannot parse pm2 jlist.'; else pm2 jlist 2>/dev/null | python3 -c 'import json, sys; apps=json.loads(sys.stdin.read() or \"[]\"); print(\"No PM2 apps.\") if not apps else [print(\" | \".join([str(app.get(\"pm_id\", \"\")), str(app.get(\"name\", \"\")), str((app.get(\"pm2_env\") or {}).get(\"status\", \"\")), \"pid=\" + str(app.get(\"pid\", \"\")), \"restart=\" + str((app.get(\"pm2_env\") or {}).get(\"restart_time\", \"\"))])) for app in apps]' 2>/dev/null || echo 'Cannot parse pm2 jlist'; fi"
  cmd "Docker containers" "if ! command -v docker >/dev/null 2>&1; then echo 'Docker not found.'; else output=\"\$(docker ps -a --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}\t{{.Image}}' 2>&1)\" && printf '%s\n' \"\$output\" || { echo 'Docker command failed. Current process may not have permission to access the Docker daemon.'; printf '%s\n' \"\$output\"; }; fi"
  write_nginx_routes_summary
}

write_package_summary() {
  local dir="$1"
  project_cmd "package.json compact summary" "$dir" "python3 -c 'import json; p=json.load(open(\"package.json\", encoding=\"utf-8\")); deps=p.get(\"dependencies\") or {}; dev=p.get(\"devDependencies\") or {}; all_deps={**deps, **dev}; keys=[\"next\",\"react\",\"express\",\"vite\",\"vue\",\"nuxt\",\"koa\",\"fastify\",\"nestjs\",\"drizzle-orm\",\"prisma\",\"pg\",\"mysql2\",\"mongoose\",\"typescript\"]; exact={\"dev\",\"start\",\"build\",\"test\",\"lint\",\"ts-check\",\"serve\",\"prod\",\"production\",\"deploy\",\"worker\",\"preview\"}; tokens=[\"serve\",\"prod\",\"deploy\",\"worker\",\"preview\"]; raw_scripts=p.get(\"scripts\") or {}; scripts={k:v for k,v in raw_scripts.items() if k in exact or k.startswith((\"db:\",\"pm2:\")) or any(t in k.lower() for t in tokens)}; summary={\"name\":p.get(\"name\"),\"version\":p.get(\"version\"),\"scripts\":scripts,\"hiddenScriptsCount\":max(len(raw_scripts)-len(scripts),0),\"dependenciesCount\":len(deps),\"devDependenciesCount\":len(dev),\"frameworkHints\":[k for k in keys if k in all_deps]}; print(json.dumps(summary, ensure_ascii=False, indent=2))' 2>/dev/null || echo 'Cannot parse package.json'"
}

write_project_summary() {
  local dir="$1"
  local git_remote="no .git"
  local git_branch="no .git"
  local git_dirty="no .git"
  local last_commit="no .git"
  local env_files

  if [ -d "$dir/.git" ]; then
    git_remote="$( (cd -- "$dir" && git remote -v 2>/dev/null | head -1) || true )"
    git_branch="$( (cd -- "$dir" && git branch --show-current 2>/dev/null) || true )"
    last_commit="$( (cd -- "$dir" && git log --oneline -1 2>/dev/null) || true )"
    if [ -n "$( (cd -- "$dir" && git status --short 2>/dev/null) || true )" ]; then
      git_dirty="yes"
    else
      git_dirty="no"
    fi
  fi

  env_files="$( (cd -- "$dir" && find . -maxdepth 2 -name '.env*' -type f -print 2>/dev/null | sed 's#^./##' | awk 'BEGIN { first=1 } { if (!first) printf ", "; printf "%s", $0; first=0 } END { if (!first) printf "\n" }') || true )"
  [ -n "$env_files" ] || env_files="none"

  write "### Project: \`$dir\`"
  write ""
  write "- Git remote: $git_remote"
  write "- Git branch: $git_branch"
  write "- Git dirty: $git_dirty"
  write "- Last commit: $last_commit"
  write "- package.json: $(has_file "$dir" "package.json")"
  write "- Dockerfile: $(has_file "$dir" "Dockerfile")"
  write "- Docker compose: $(has_any_compose_file "$dir")"
  write "- PM2 ecosystem: $(has_file "$dir" "ecosystem.config.js")"
  write "- Env files names only: $env_files"
  write ""

  if [ -f "$dir/package.json" ]; then
    write_package_summary "$dir"
  fi
}

write_summary_projects() {
  section "5. Detected Projects"

  local project_dirs
  project_dirs="$(safe_project_dirs || true)"

  if [ -z "$project_dirs" ]; then
    write "No project directories detected under /opt or \$HOME."
    write ""
    return
  fi

  while IFS= read -r dir; do
    [ -z "$dir" ] && continue
    write_project_summary "$dir"
  done <<< "$project_dirs"
}

write_summary_risks() {
  section "6. Quick Risk Signals"
  write "- Disk warning threshold: check root disk use above 80%."
  write "- Memory warning threshold: check low available memory or heavy swap use."
  write "- Port conflicts: occupied common ports are listed in section 3."
  write "- Nginx duplicate server_name: inspect Nginx warnings or run \`sudo nginx -t\` before changing config."
  write "- Hidden secrets: .env file names are listed, values are not scanned."
}

write_ai_instructions() {
  section "AI Reading Instructions"
  write "Please analyze this report based only on visible evidence."
  write ""
  write "Focus on:"
  write ""
  write "- Existing projects and their likely runtime method."
  write "- Occupied ports and possible conflicts."
  write "- Whether Node/npm/PM2/Docker/Nginx are available."
  write "- Whether a new project can be safely added."
  write "- Recommended directory, port, process manager, and Nginx strategy."
  write "- Do not assume hidden .env values."
  write "- Treat permission errors as insufficient evidence, not as proof of absence."
  write "- Do not recommend destructive commands unless explicitly requested."
  write ""
}

scan_summary() {
  init_report "Server Context Summary"
  write_summary_host
  write_summary_runtime
  write_summary_ports
  write_summary_services
  write_summary_projects
  write_summary_risks
  write_ai_instructions
}

scan_full() {
  init_report "Server Context Full Diagnostic Report"

  section "1. Basic System"
  cmd "Current user and path" "whoami; pwd; hostname; date; uptime"
  cmd "OS information" "uname -a; echo; if [ -f /etc/os-release ]; then cat /etc/os-release; fi"
  cmd "CPU / Memory / Disk" "echo 'CPU cores:'; nproc || true; echo; echo 'Memory:'; free -h || true; echo; echo 'Disk:'; df -h || true"

  section "2. Runtime Environment"
  cmd "Node / npm / npx" "which node || true; node -v || true; which npm || true; npm -v || true; which npx || true; npx -v || true"
  cmd "Git" "which git || true; git --version || true"
  cmd "Python" "which python3 || true; python3 --version || true; which pip3 || true; pip3 --version || true"
  cmd "PM2" "which pm2 || true; pm2 -v || true; pm2 status || true"
  cmd "Docker" "which docker || true; docker --version || true; docker compose version || true; docker ps -a || true"
  cmd "Systemd" "which systemctl || true; systemctl --version 2>/dev/null | head -5 || true"
  cmd "Nginx" "which nginx || true; nginx -v || true; systemctl status nginx --no-pager || true"

  section "3. Ports and Listening Services"
  cmd "Listening TCP ports" "ss -lntp || netstat -lntp || true"
  cmd "Common ports quick check" "for p in 80 443 3000 3001 3010 3011 5000 5173 8000 8080; do echo \"--- port \$p ---\"; ss -lntp 2>/dev/null | grep \":\$p \" || true; done"

  section "4. Common Project Directories"
  cmd "/opt directory" "ls -la /opt || true"
  cmd "Home directory top-level directories" "find \"$HOME\" -maxdepth 1 -type d -printf '%f\n' 2>/dev/null | sort || true"

  section "5. Detected Project Directories"

  local project_dirs
  project_dirs="$(safe_project_dirs || true)"

  if [ -z "$project_dirs" ]; then
    write "No project directories detected under /opt or \$HOME."
    write ""
  else
    while IFS= read -r dir; do
      [ -z "$dir" ] && continue

      write "### Project: \`$dir\`"
      write ""

      project_cmd "Files in $dir" "$dir" "ls -la"

      if [ -d "$dir/.git" ]; then
        project_cmd "Git status for $dir" "$dir" "git remote -v || true; git branch --show-current || true; git log --oneline -5 || true; git status --short || true"
      else
        write "- Git: No .git directory found."
        write ""
      fi

      if [ -f "$dir/package.json" ]; then
        project_cmd "package.json full summary for $dir" "$dir" "python3 -c 'import json; p=json.load(open(\"package.json\", encoding=\"utf-8\")); deps=p.get(\"dependencies\") or {}; dev=p.get(\"devDependencies\") or {}; summary={\"name\":p.get(\"name\"),\"version\":p.get(\"version\"),\"scripts\":p.get(\"scripts\"),\"dependencies\":list(deps.keys()),\"devDependencies\":list(dev.keys())}; print(json.dumps(summary, ensure_ascii=False, indent=2))' 2>/dev/null || echo 'Cannot parse package.json'"
      fi

      if [ -f "$dir/docker-compose.yml" ] || [ -f "$dir/docker-compose.yaml" ] || [ -f "$dir/compose.yml" ] || [ -f "$dir/compose.yaml" ]; then
        project_cmd "Docker compose status for $dir" "$dir" "docker compose ps || true"
      fi

      if [ -f "$dir/Dockerfile" ]; then
        project_cmd "Dockerfile detected for $dir" "$dir" "ls -la Dockerfile"
      fi

      if [ -f "$dir/ecosystem.config.js" ]; then
        project_cmd "PM2 ecosystem file detected for $dir" "$dir" "ls -la ecosystem.config.js"
      fi

      project_cmd "Env files names only for $dir" "$dir" "find . -maxdepth 2 -name '.env*' -type f -print | sed 's#^./##' || true"
    done <<< "$project_dirs"
  fi

  section "6. Nginx Site Entry Summary"
  cmd "Nginx enabled sites and proxy rules" "grep -R \"server_name\\|listen\\|proxy_pass\" /etc/nginx/sites-enabled /etc/nginx/conf.d 2>/dev/null || true"

  section "7. Process Summary"
  cmd "Node / npm / pm2 / next / vite processes" "ps aux | grep -E 'node|npm|pm2|next|vite' | grep -v grep || true"
  cmd "Docker related processes" "ps aux | grep -E 'dockerd|containerd' | grep -v grep || true"

  section "8. Environment Variable Names Only"
  cmd "Environment variable names" "printenv | cut -d= -f1 | sort || true"

  write_ai_instructions
}

if [ "$MODE" = "full" ]; then
  scan_full
else
  scan_summary
fi

cp "$REPORT_FILE" "$LATEST_FILE"

echo "Report generated:"
echo "$REPORT_FILE"
echo ""
echo "Latest report:"
echo "$LATEST_FILE"
