#!/usr/bin/env bash

set -u

APP_DIR="${SERVER_CONTEXT_SCANNER_HOME:-$HOME/server-context-scanner}"
REPORT_DIR="$APP_DIR/reports"
mkdir -p "$REPORT_DIR"

TS="$(date '+%Y%m%d_%H%M%S')"
REPORT_FILE="$REPORT_DIR/server_context_$TS.md"
LATEST_FILE="$REPORT_DIR/server_context_latest.md"

write() {
  printf '%s\n' "$*" >> "$REPORT_FILE"
}

section() {
  write ""
  write "## $1"
  write ""
}

cmd() {
  local title="$1"
  local command="$2"

  write "### $title"
  write ""
  write '```bash'
  write "$ $command"
  write '```'
  write ""
  write '```text'
  bash -lc "$command" >> "$REPORT_FILE" 2>&1 || true
  write '```'
  write ""
}

safe_project_dirs() {
  find /opt "$HOME" \
    -maxdepth 4 \
    -type f \( \
      -name "package.json" -o \
      -name "docker-compose.yml" -o \
      -name "docker-compose.yaml" -o \
      -name "compose.yml" -o \
      -name "compose.yaml" -o \
      -name "Dockerfile" -o \
      -name "ecosystem.config.js" \
    \) \
    -not -path "*/node_modules/*" \
    -not -path "*/.cache/*" \
    -not -path "*/reports/*" \
    -not -path "*/.npm/*" \
    -not -path "*/.local/*" \
    2>/dev/null \
    | xargs -r dirname \
    | sort -u
}

{
  echo "# Server Context Report"
  echo ""
  echo "- Generated at: $(date '+%Y-%m-%d %H:%M:%S %Z')"
  echo "- Hostname: $(hostname 2>/dev/null || true)"
  echo "- User: $(whoami 2>/dev/null || true)"
  echo "- Scanner directory: $APP_DIR"
  echo "- Report file: $REPORT_FILE"
  echo ""
  echo "> This report is generated by a read-only scanner. It should not include secret values."
  echo "> Permission denied output means the current user cannot inspect that resource; it does not prove the resource does not exist."
} > "$REPORT_FILE"

section "1. Basic System"
cmd "Current user and path" "whoami; pwd; hostname; date; uptime"
cmd "OS information" "uname -a; echo; if [ -f /etc/os-release ]; then cat /etc/os-release; fi"
cmd "CPU / Memory / Disk" "echo 'CPU cores:'; nproc || true; echo; echo 'Memory:'; free -h || true; echo; echo 'Disk:'; df -h || true"

section "2. Runtime Environment"
cmd "Node / npm / npx" "which node || true; node -v || true; which npm || true; npm -v || true; which npx || true; npx -v || true"
cmd "Git" "which git || true; git --version || true"
cmd "Python" "which python3 || true; python3 --version || true; which pip3 || true; pip3 --version || true"
cmd "PM2" "which pm2 || true; pm2 -v || true; pm2 status || true"
cmd "Docker" "which docker || true; docker --version || true; docker compose version || true; docker ps -a || true"
cmd "Systemd" "which systemctl || true; systemctl --version 2>/dev/null | head -5 || true"
cmd "Nginx" "which nginx || true; nginx -v || true; systemctl status nginx --no-pager || true"

section "3. Ports and Listening Services"
cmd "Listening TCP ports" "ss -lntp || netstat -lntp || true"
cmd "Common ports quick check" "for p in 80 443 3000 3001 3010 5000 5173 8000 8080; do echo \"--- port \$p ---\"; ss -lntp 2>/dev/null | grep \":\$p \" || true; done"

section "4. Common Project Directories"
cmd "/opt directory" "ls -la /opt || true"
cmd "Home directory top-level files" "ls -la \"$HOME\" || true"

section "5. Detected Project Directories"

PROJECT_DIRS="$(safe_project_dirs || true)"

if [ -z "$PROJECT_DIRS" ]; then
  write "No project directories detected under /opt or \$HOME."
  write ""
else
  while IFS= read -r dir; do
    [ -z "$dir" ] && continue

    write "### Project: \`$dir\`"
    write ""

    cmd "Files in $dir" "cd '$dir' && ls -la"

    if [ -d "$dir/.git" ]; then
      cmd "Git status for $dir" "cd '$dir' && git remote -v || true; git branch --show-current || true; git log --oneline -5 || true; git status --short || true"
    else
      write "- Git: No .git directory found."
      write ""
    fi

    if [ -f "$dir/package.json" ]; then
      cmd "package.json summary for $dir" "cd '$dir' && node -e \"const p=require('./package.json'); console.log(JSON.stringify({name:p.name, version:p.version, scripts:p.scripts, dependencies:Object.keys(p.dependencies||{}), devDependencies:Object.keys(p.devDependencies||{})}, null, 2))\" 2>/dev/null || echo 'Cannot parse package.json'"
    fi

    if [ -f "$dir/docker-compose.yml" ] || [ -f "$dir/docker-compose.yaml" ] || [ -f "$dir/compose.yml" ] || [ -f "$dir/compose.yaml" ]; then
      cmd "Docker compose status for $dir" "cd '$dir' && docker compose ps || true"
    fi

    if [ -f "$dir/Dockerfile" ]; then
      cmd "Dockerfile detected for $dir" "cd '$dir' && ls -la Dockerfile"
    fi

    if [ -f "$dir/ecosystem.config.js" ]; then
      cmd "PM2 ecosystem file detected for $dir" "cd '$dir' && ls -la ecosystem.config.js"
    fi

    cmd "Env files names only for $dir" "cd '$dir' && find . -maxdepth 2 -name '.env*' -type f -print | sed 's#^./##' || true"
  done <<< "$PROJECT_DIRS"
fi

section "6. Nginx Site Entry Summary"
cmd "Nginx enabled sites and proxy rules" "grep -R \"server_name\\|listen\\|proxy_pass\" /etc/nginx/sites-enabled /etc/nginx/conf.d 2>/dev/null || true"

section "7. Process Summary"
cmd "Node / npm / pm2 / next / vite processes" "ps aux | grep -E 'node|npm|pm2|next|vite' | grep -v grep || true"
cmd "Docker related processes" "ps aux | grep -E 'dockerd|containerd' | grep -v grep || true"

section "8. Environment Variable Names Only"
cmd "Environment variable names" "printenv | cut -d= -f1 | sort || true"

section "9. AI Reading Instructions"
write "Please analyze this report based only on visible evidence."
write ""
write "Focus on:"
write ""
write "- Existing projects and their likely runtime method."
write "- Occupied ports and possible conflicts."
write "- Whether Node/npm/PM2/Docker/Nginx are available."
write "- Whether a new project can be safely added."
write "- Recommended directory, port, process manager, and Nginx strategy."
write "- Do not assume hidden .env values."
write "- Treat permission errors as insufficient evidence, not as proof of absence."
write "- Do not recommend destructive commands unless explicitly requested."
write ""

cp "$REPORT_FILE" "$LATEST_FILE"

echo "Report generated:"
echo "$REPORT_FILE"
echo ""
echo "Latest report:"
echo "$LATEST_FILE"
